name: BioJS
description: Represent all biological data on the web
url: http://biojs.net
markdown: kramdown
#pygments: false
#highlighter: pygments
timezone: UTC
encoding: utf-8
exclude: [vendor]
series:
    "101":
      desc: "Basics"
      sort: 1
    "snipspector":
      desc: "Snipspector"
      sort: 2
    "102":
      desc: "Advanced series"
      sort: 3
