name: BioJS
description: Represent all biological data on the web
url: http://biojs.net
markdown: kramdown
#pygments: false
#highlighter: pygments
timezone: UTC
encoding: utf-8
exclude: [vendor]
series:
    "101":
      desc: "Beginner series (101)"
      sort: 1
    "102":
      desc: "Advanced series (102)"
      sort: 2
    "snipspector":
      desc: "Snipspector"
      sort: 3
